# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Siddhartha Dimania
title: Software Engineer
email: siddimania@gmail.com
#website: https://siddimania.github.io/

# Social links
#twitter_username: facespics
github_username:  siddimania
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: siddimania
linkedin_username: siddimania
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Siddhartha and I'm a software engineer. I have experience making software and mobile application. I have worked at a few companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Ruby</mark>, <mark>Java</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software development some of my other interests and hobbies are:
   - Paiting
   - Gaming
   - Becoming a ninja

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
